project:
  type: manuscript

manuscript:
  article: proposal.qmd

format:
  html:
    number-sections: true

  revealjs:
    theme: default
    output-file: slides.html
    transition: fade
    slide-number: true
    slide-level: 3
    footer: "[Back to Page](https://dmoored4.github.io/data-mining-term-project/)"
    logo: assets/R_sunj.svg

  typst:
    number-sections: true
    logo: assets/R_sunj.svg
